// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Example {

  /// <summary>Holder for reflection information generated from Protocol_v3.proto</summary>
  public static partial class ProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90b2NvbF92My5wcm90bxILb3JnLmV4YW1wbGUiMwoRUGVyc29hbmFP",
            "ZmljaXVEdG8SDAoEbmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSI+ChVQ",
            "YXJ0aWNpcGFudHNCeVJhY2VEdG8SDQoFY3Vyc2EYASABKAkSFgoObnJQYXJ0",
            "aWNpcGFudGkYAiABKAUiPgoXVGVhbXNBbmRQYXJ0aWNpcGFudHNEdG8SDgoG",
            "ZWNoaXBhGAEgASgJEhMKC3BhcnRpY2lwYW50GAIgASgJIr0CCg1DbGllbnRS",
            "ZXF1ZXN0Ei0KBHR5cGUYASABKA4yHy5vcmcuZXhhbXBsZS5DbGllbnRSZXF1",
            "ZXN0LlR5cGUSLAoEdXNlchgCIAEoCzIeLm9yZy5leGFtcGxlLlBlcnNvYW5h",
            "T2ZpY2l1RHRvEhoKEnBlcnNvYW5hT2ZpY2l1TmFtZRgDIAEoCRISCgpudW1l",
            "RWNoaXBhGAQgASgJEhcKD251bWVQYXJ0aWNpcGFudBgFIAEoCRIRCgludW1l",
            "Q3Vyc2EYByABKAkicwoEVHlwZRIKCgZVbmtvd24QABIJCgVMT0dJThABEhMK",
            "D05FV19QQVJUSUNJUEFOVBACEhoKFk5SX1BBUlRJQ0lQQU5UU19CWVJBQ0UQ",
            "AxIXChNQQVJUSUNJUEFOVFNfQllURUFNEAQSCgoGTE9HT1VUEAUipwMKDkNs",
            "aWVudFJlc3BvbnNlEi4KBHR5cGUYASABKA4yIC5vcmcuZXhhbXBsZS5DbGll",
            "bnRSZXNwb25zZS5UeXBlEg0KBWVycm9yGAIgASgJEkEKFXBhcnRpY2lwYW50",
            "c0J5UmFjZUR0bxgDIAMoCzIiLm9yZy5leGFtcGxlLlBhcnRpY2lwYW50c0J5",
            "UmFjZUR0bxJAChRwYXJ0aWNpcGFudEJ5UmFjZUR0bxgEIAEoCzIiLm9yZy5l",
            "eGFtcGxlLlBhcnRpY2lwYW50c0J5UmFjZUR0bxJFChd0ZWFtc0FuZFBhcnRp",
            "Y2lwYW50c0R0bxgFIAMoCzIkLm9yZy5leGFtcGxlLlRlYW1zQW5kUGFydGlj",
            "aXBhbnRzRHRvEkQKFnRlYW1BbmRQYXJ0aWNpcGFudHNEdG8YBiABKAsyJC5v",
            "cmcuZXhhbXBsZS5UZWFtc0FuZFBhcnRpY2lwYW50c0R0byJECgRUeXBlEgsK",
            "B1Vua25vd24QABIGCgJPSxABEgkKBUVSUk9SEAISHAoYUEVSU09BTkFPRklD",
            "SVVfTE9HR0VEX0lOEANCKgodb3JnLmV4YW1wbGUucHJvdG9idWZmcHJvdG9j",
            "b2xCCVByb3RvYnVmc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.PersoanaOficiuDto), global::Org.Example.PersoanaOficiuDto.Parser, new[]{ "Name", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.ParticipantsByRaceDto), global::Org.Example.ParticipantsByRaceDto.Parser, new[]{ "Cursa", "NrParticipanti" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.TeamsAndParticipantsDto), global::Org.Example.TeamsAndParticipantsDto.Parser, new[]{ "Echipa", "Participant" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.ClientRequest), global::Org.Example.ClientRequest.Parser, new[]{ "Type", "User", "PersoanaOficiuName", "NumeEchipa", "NumeParticipant", "NumeCursa" }, null, new[]{ typeof(global::Org.Example.ClientRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Example.ClientResponse), global::Org.Example.ClientResponse.Parser, new[]{ "Type", "Error", "ParticipantsByRaceDto", "ParticipantByRaceDto", "TeamsAndParticipantsDto", "TeamAndParticipantsDto" }, null, new[]{ typeof(global::Org.Example.ClientResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PersoanaOficiuDto : pb::IMessage<PersoanaOficiuDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PersoanaOficiuDto> _parser = new pb::MessageParser<PersoanaOficiuDto>(() => new PersoanaOficiuDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PersoanaOficiuDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersoanaOficiuDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersoanaOficiuDto(PersoanaOficiuDto other) : this() {
      name_ = other.name_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersoanaOficiuDto Clone() {
      return new PersoanaOficiuDto(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PersoanaOficiuDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PersoanaOficiuDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PersoanaOficiuDto other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ParticipantsByRaceDto : pb::IMessage<ParticipantsByRaceDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticipantsByRaceDto> _parser = new pb::MessageParser<ParticipantsByRaceDto>(() => new ParticipantsByRaceDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticipantsByRaceDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantsByRaceDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantsByRaceDto(ParticipantsByRaceDto other) : this() {
      cursa_ = other.cursa_;
      nrParticipanti_ = other.nrParticipanti_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantsByRaceDto Clone() {
      return new ParticipantsByRaceDto(this);
    }

    /// <summary>Field number for the "cursa" field.</summary>
    public const int CursaFieldNumber = 1;
    private string cursa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cursa {
      get { return cursa_; }
      set {
        cursa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrParticipanti" field.</summary>
    public const int NrParticipantiFieldNumber = 2;
    private int nrParticipanti_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrParticipanti {
      get { return nrParticipanti_; }
      set {
        nrParticipanti_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticipantsByRaceDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticipantsByRaceDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cursa != other.Cursa) return false;
      if (NrParticipanti != other.NrParticipanti) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cursa.Length != 0) hash ^= Cursa.GetHashCode();
      if (NrParticipanti != 0) hash ^= NrParticipanti.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cursa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cursa);
      }
      if (NrParticipanti != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NrParticipanti);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cursa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cursa);
      }
      if (NrParticipanti != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NrParticipanti);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cursa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cursa);
      }
      if (NrParticipanti != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrParticipanti);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticipantsByRaceDto other) {
      if (other == null) {
        return;
      }
      if (other.Cursa.Length != 0) {
        Cursa = other.Cursa;
      }
      if (other.NrParticipanti != 0) {
        NrParticipanti = other.NrParticipanti;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cursa = input.ReadString();
            break;
          }
          case 16: {
            NrParticipanti = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Cursa = input.ReadString();
            break;
          }
          case 16: {
            NrParticipanti = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeamsAndParticipantsDto : pb::IMessage<TeamsAndParticipantsDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamsAndParticipantsDto> _parser = new pb::MessageParser<TeamsAndParticipantsDto>(() => new TeamsAndParticipantsDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamsAndParticipantsDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamsAndParticipantsDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamsAndParticipantsDto(TeamsAndParticipantsDto other) : this() {
      echipa_ = other.echipa_;
      participant_ = other.participant_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamsAndParticipantsDto Clone() {
      return new TeamsAndParticipantsDto(this);
    }

    /// <summary>Field number for the "echipa" field.</summary>
    public const int EchipaFieldNumber = 1;
    private string echipa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Echipa {
      get { return echipa_; }
      set {
        echipa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 2;
    private string participant_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Participant {
      get { return participant_; }
      set {
        participant_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamsAndParticipantsDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamsAndParticipantsDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Echipa != other.Echipa) return false;
      if (Participant != other.Participant) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Echipa.Length != 0) hash ^= Echipa.GetHashCode();
      if (Participant.Length != 0) hash ^= Participant.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Echipa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Echipa);
      }
      if (Participant.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Participant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Echipa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Echipa);
      }
      if (Participant.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Participant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Echipa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Echipa);
      }
      if (Participant.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Participant);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamsAndParticipantsDto other) {
      if (other == null) {
        return;
      }
      if (other.Echipa.Length != 0) {
        Echipa = other.Echipa;
      }
      if (other.Participant.Length != 0) {
        Participant = other.Participant;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Echipa = input.ReadString();
            break;
          }
          case 18: {
            Participant = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Echipa = input.ReadString();
            break;
          }
          case 18: {
            Participant = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientRequest : pb::IMessage<ClientRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest(ClientRequest other) : this() {
      type_ = other.type_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      persoanaOficiuName_ = other.persoanaOficiuName_;
      numeEchipa_ = other.numeEchipa_;
      numeParticipant_ = other.numeParticipant_;
      numeCursa_ = other.numeCursa_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest Clone() {
      return new ClientRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Org.Example.ClientRequest.Types.Type type_ = global::Org.Example.ClientRequest.Types.Type.Unkown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.ClientRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private global::Org.Example.PersoanaOficiuDto user_;
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.PersoanaOficiuDto User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "persoanaOficiuName" field.</summary>
    public const int PersoanaOficiuNameFieldNumber = 3;
    private string persoanaOficiuName_ = "";
    /// <summary>
    /// pentru LOGOUT persoanaOficiu
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PersoanaOficiuName {
      get { return persoanaOficiuName_; }
      set {
        persoanaOficiuName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeEchipa" field.</summary>
    public const int NumeEchipaFieldNumber = 4;
    private string numeEchipa_ = "";
    /// <summary>
    /// pentru FILTRARE PARTICIPANTI DUPA ECHIPA
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeEchipa {
      get { return numeEchipa_; }
      set {
        numeEchipa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeParticipant" field.</summary>
    public const int NumeParticipantFieldNumber = 5;
    private string numeParticipant_ = "";
    /// <summary>
    /// adaugare nou participant
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeParticipant {
      get { return numeParticipant_; }
      set {
        numeParticipant_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeCursa" field.</summary>
    public const int NumeCursaFieldNumber = 7;
    private string numeCursa_ = "";
    /// <summary>
    ///    string numeEchipa = 6;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeCursa {
      get { return numeCursa_; }
      set {
        numeCursa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (PersoanaOficiuName != other.PersoanaOficiuName) return false;
      if (NumeEchipa != other.NumeEchipa) return false;
      if (NumeParticipant != other.NumeParticipant) return false;
      if (NumeCursa != other.NumeCursa) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Org.Example.ClientRequest.Types.Type.Unkown) hash ^= Type.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (PersoanaOficiuName.Length != 0) hash ^= PersoanaOficiuName.GetHashCode();
      if (NumeEchipa.Length != 0) hash ^= NumeEchipa.GetHashCode();
      if (NumeParticipant.Length != 0) hash ^= NumeParticipant.GetHashCode();
      if (NumeCursa.Length != 0) hash ^= NumeCursa.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Org.Example.ClientRequest.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (PersoanaOficiuName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PersoanaOficiuName);
      }
      if (NumeEchipa.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NumeEchipa);
      }
      if (NumeParticipant.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeParticipant);
      }
      if (NumeCursa.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(NumeCursa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Org.Example.ClientRequest.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (PersoanaOficiuName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PersoanaOficiuName);
      }
      if (NumeEchipa.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NumeEchipa);
      }
      if (NumeParticipant.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeParticipant);
      }
      if (NumeCursa.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(NumeCursa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Org.Example.ClientRequest.Types.Type.Unkown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (PersoanaOficiuName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PersoanaOficiuName);
      }
      if (NumeEchipa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeEchipa);
      }
      if (NumeParticipant.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeParticipant);
      }
      if (NumeCursa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeCursa);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Org.Example.ClientRequest.Types.Type.Unkown) {
        Type = other.Type;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Org.Example.PersoanaOficiuDto();
        }
        User.MergeFrom(other.User);
      }
      if (other.PersoanaOficiuName.Length != 0) {
        PersoanaOficiuName = other.PersoanaOficiuName;
      }
      if (other.NumeEchipa.Length != 0) {
        NumeEchipa = other.NumeEchipa;
      }
      if (other.NumeParticipant.Length != 0) {
        NumeParticipant = other.NumeParticipant;
      }
      if (other.NumeCursa.Length != 0) {
        NumeCursa = other.NumeCursa;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Org.Example.ClientRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::Org.Example.PersoanaOficiuDto();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            PersoanaOficiuName = input.ReadString();
            break;
          }
          case 34: {
            NumeEchipa = input.ReadString();
            break;
          }
          case 42: {
            NumeParticipant = input.ReadString();
            break;
          }
          case 58: {
            NumeCursa = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Org.Example.ClientRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::Org.Example.PersoanaOficiuDto();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            PersoanaOficiuName = input.ReadString();
            break;
          }
          case 34: {
            NumeEchipa = input.ReadString();
            break;
          }
          case 42: {
            NumeParticipant = input.ReadString();
            break;
          }
          case 58: {
            NumeCursa = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ClientRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unkown")] Unkown = 0,
        [pbr::OriginalName("LOGIN")] Login = 1,
        [pbr::OriginalName("NEW_PARTICIPANT")] NewParticipant = 2,
        [pbr::OriginalName("NR_PARTICIPANTS_BYRACE")] NrParticipantsByrace = 3,
        [pbr::OriginalName("PARTICIPANTS_BYTEAM")] ParticipantsByteam = 4,
        [pbr::OriginalName("LOGOUT")] Logout = 5,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientResponse : pb::IMessage<ClientResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientResponse> _parser = new pb::MessageParser<ClientResponse>(() => new ClientResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Example.ProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientResponse(ClientResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      participantsByRaceDto_ = other.participantsByRaceDto_.Clone();
      participantByRaceDto_ = other.participantByRaceDto_ != null ? other.participantByRaceDto_.Clone() : null;
      teamsAndParticipantsDto_ = other.teamsAndParticipantsDto_.Clone();
      teamAndParticipantsDto_ = other.teamAndParticipantsDto_ != null ? other.teamAndParticipantsDto_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientResponse Clone() {
      return new ClientResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Org.Example.ClientResponse.Types.Type type_ = global::Org.Example.ClientResponse.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.ClientResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participantsByRaceDto" field.</summary>
    public const int ParticipantsByRaceDtoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Org.Example.ParticipantsByRaceDto> _repeated_participantsByRaceDto_codec
        = pb::FieldCodec.ForMessage(26, global::Org.Example.ParticipantsByRaceDto.Parser);
    private readonly pbc::RepeatedField<global::Org.Example.ParticipantsByRaceDto> participantsByRaceDto_ = new pbc::RepeatedField<global::Org.Example.ParticipantsByRaceDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Example.ParticipantsByRaceDto> ParticipantsByRaceDto {
      get { return participantsByRaceDto_; }
    }

    /// <summary>Field number for the "participantByRaceDto" field.</summary>
    public const int ParticipantByRaceDtoFieldNumber = 4;
    private global::Org.Example.ParticipantsByRaceDto participantByRaceDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.ParticipantsByRaceDto ParticipantByRaceDto {
      get { return participantByRaceDto_; }
      set {
        participantByRaceDto_ = value;
      }
    }

    /// <summary>Field number for the "teamsAndParticipantsDto" field.</summary>
    public const int TeamsAndParticipantsDtoFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Org.Example.TeamsAndParticipantsDto> _repeated_teamsAndParticipantsDto_codec
        = pb::FieldCodec.ForMessage(42, global::Org.Example.TeamsAndParticipantsDto.Parser);
    private readonly pbc::RepeatedField<global::Org.Example.TeamsAndParticipantsDto> teamsAndParticipantsDto_ = new pbc::RepeatedField<global::Org.Example.TeamsAndParticipantsDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Example.TeamsAndParticipantsDto> TeamsAndParticipantsDto {
      get { return teamsAndParticipantsDto_; }
    }

    /// <summary>Field number for the "teamAndParticipantsDto" field.</summary>
    public const int TeamAndParticipantsDtoFieldNumber = 6;
    private global::Org.Example.TeamsAndParticipantsDto teamAndParticipantsDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Example.TeamsAndParticipantsDto TeamAndParticipantsDto {
      get { return teamAndParticipantsDto_; }
      set {
        teamAndParticipantsDto_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!participantsByRaceDto_.Equals(other.participantsByRaceDto_)) return false;
      if (!object.Equals(ParticipantByRaceDto, other.ParticipantByRaceDto)) return false;
      if(!teamsAndParticipantsDto_.Equals(other.teamsAndParticipantsDto_)) return false;
      if (!object.Equals(TeamAndParticipantsDto, other.TeamAndParticipantsDto)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Org.Example.ClientResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= participantsByRaceDto_.GetHashCode();
      if (participantByRaceDto_ != null) hash ^= ParticipantByRaceDto.GetHashCode();
      hash ^= teamsAndParticipantsDto_.GetHashCode();
      if (teamAndParticipantsDto_ != null) hash ^= TeamAndParticipantsDto.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Org.Example.ClientResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      participantsByRaceDto_.WriteTo(output, _repeated_participantsByRaceDto_codec);
      if (participantByRaceDto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ParticipantByRaceDto);
      }
      teamsAndParticipantsDto_.WriteTo(output, _repeated_teamsAndParticipantsDto_codec);
      if (teamAndParticipantsDto_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TeamAndParticipantsDto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Org.Example.ClientResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      participantsByRaceDto_.WriteTo(ref output, _repeated_participantsByRaceDto_codec);
      if (participantByRaceDto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ParticipantByRaceDto);
      }
      teamsAndParticipantsDto_.WriteTo(ref output, _repeated_teamsAndParticipantsDto_codec);
      if (teamAndParticipantsDto_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TeamAndParticipantsDto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Org.Example.ClientResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += participantsByRaceDto_.CalculateSize(_repeated_participantsByRaceDto_codec);
      if (participantByRaceDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantByRaceDto);
      }
      size += teamsAndParticipantsDto_.CalculateSize(_repeated_teamsAndParticipantsDto_codec);
      if (teamAndParticipantsDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TeamAndParticipantsDto);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Org.Example.ClientResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      participantsByRaceDto_.Add(other.participantsByRaceDto_);
      if (other.participantByRaceDto_ != null) {
        if (participantByRaceDto_ == null) {
          ParticipantByRaceDto = new global::Org.Example.ParticipantsByRaceDto();
        }
        ParticipantByRaceDto.MergeFrom(other.ParticipantByRaceDto);
      }
      teamsAndParticipantsDto_.Add(other.teamsAndParticipantsDto_);
      if (other.teamAndParticipantsDto_ != null) {
        if (teamAndParticipantsDto_ == null) {
          TeamAndParticipantsDto = new global::Org.Example.TeamsAndParticipantsDto();
        }
        TeamAndParticipantsDto.MergeFrom(other.TeamAndParticipantsDto);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Org.Example.ClientResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            participantsByRaceDto_.AddEntriesFrom(input, _repeated_participantsByRaceDto_codec);
            break;
          }
          case 34: {
            if (participantByRaceDto_ == null) {
              ParticipantByRaceDto = new global::Org.Example.ParticipantsByRaceDto();
            }
            input.ReadMessage(ParticipantByRaceDto);
            break;
          }
          case 42: {
            teamsAndParticipantsDto_.AddEntriesFrom(input, _repeated_teamsAndParticipantsDto_codec);
            break;
          }
          case 50: {
            if (teamAndParticipantsDto_ == null) {
              TeamAndParticipantsDto = new global::Org.Example.TeamsAndParticipantsDto();
            }
            input.ReadMessage(TeamAndParticipantsDto);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Org.Example.ClientResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            participantsByRaceDto_.AddEntriesFrom(ref input, _repeated_participantsByRaceDto_codec);
            break;
          }
          case 34: {
            if (participantByRaceDto_ == null) {
              ParticipantByRaceDto = new global::Org.Example.ParticipantsByRaceDto();
            }
            input.ReadMessage(ParticipantByRaceDto);
            break;
          }
          case 42: {
            teamsAndParticipantsDto_.AddEntriesFrom(ref input, _repeated_teamsAndParticipantsDto_codec);
            break;
          }
          case 50: {
            if (teamAndParticipantsDto_ == null) {
              TeamAndParticipantsDto = new global::Org.Example.TeamsAndParticipantsDto();
            }
            input.ReadMessage(TeamAndParticipantsDto);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ClientResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("OK")] Ok = 1,
        [pbr::OriginalName("ERROR")] Error = 2,
        [pbr::OriginalName("PERSOANAOFICIU_LOGGED_IN")] PersoanaoficiuLoggedIn = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
